version: "3.9"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      pi_project:
    volumes:
      - my-db:/var/lib/mysql
  gestionBancaire:
    build: .
    image: gestionBancaire
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - db
    networks:
      pi_project:
networks:
  mini_project:
    driver: bridge
volumes:
  my-db:
